/**
 * Test IDs Registry - MVP VERSION
 * 
 * Complete test ID registry for MVP functionality
 */

export const T = {
  // Auth related
  loginButton: 'login-button',
  registerButton: 'register-button',
  logoutButton: 'logout-button',
  
  // Poll related
  createPollButton: 'create-poll-button',
  voteButton: 'vote-button',
  pollTitle: 'poll-title',
  
  // Navigation
  navigation: 'navigation',
  userMenu: 'user-menu',
  
  // Admin
  admin: {
    accessDenied: 'admin-access-denied',
    usersTab: 'admin-users-tab',
    pollsTab: 'admin-polls-tab',
    userList: 'admin-user-list',
    pollList: 'admin-poll-list',
    promoteUser: (userId: string) => `admin-promote-user-${userId}`,
    banUser: (userId: string) => `admin-ban-user-${userId}`,
  },
  
  // Login/Register
  login: {
    email: 'login-email',
    password: 'login-password',
    submit: 'login-submit',
    form: 'auth-form',
    toggle: 'auth-toggle',
    error: 'auth-error',
    success: 'success-message',
  },
  
  // WebAuthn
  webauthn: {
    register: 'webauthn-register',
    login: 'webauthn-login',
    prompt: 'webauthn-prompt',
    features: 'webauthn-features',
    biometricButton: 'webauthn-biometric-button',
    crossDeviceButton: 'webauthn-cross-device-button',
    qr: 'webauthn-qr',
    authPrompt: 'webauthn-auth-prompt',
    biometricPrompt: 'webauthn-biometric-prompt',
    networkError: 'webauthn-network-error',
    serverError: 'webauthn-server-error',
  },
  
  // Poll Creation
  pollCreate: {
    title: 'poll-create-title',
    titleError: 'poll-create-title-error',
    description: 'poll-create-description',
    category: 'poll-create-category',
    votingMethod: 'poll-create-voting-method',
    votingMethodError: 'poll-create-voting-method-error',
    optionInput: (index: number) => `poll-create-option-input-${index}`,
    removeOption: (index: number) => `poll-create-remove-option-${index}`,
    addOption: 'poll-create-add-option',
    optionsError: 'poll-create-options-error',
    startTime: 'poll-create-start-time',
    endTime: 'poll-create-end-time',
    timingError: 'poll-create-timing-error',
    privacyLevel: 'poll-create-privacy-level',
    submit: 'poll-create-submit',
    reset: 'poll-create-reset',
  },
  
  // Generic
  submitButton: 'submit-button',
  cancelButton: 'cancel-button',
  loadingSpinner: 'loading-spinner',
  
  // PWA
  pwa: {
    status: 'pwa-status',
    installPrompt: 'pwa-install-prompt',
    installButton: 'pwa-install-button',
    installedStatus: 'pwa-installed-status',
    offlineIndicator: 'offline-indicator',
    offlineQueue: 'offline-queue',
    syncButton: 'pwa-sync-button',
    clearButton: 'pwa-clear-button',
    requestPermissionButton: 'pwa-request-permission-button',
    testNotificationButton: 'pwa-test-notification-button',
    firstFocusable: 'pwa-first-focusable',
    installingIndicator: 'pwa-installing-indicator',
    installedIndicator: 'pwa-installed-indicator',
    notificationPermission: 'pwa-notification-permission',
    notificationPreferences: 'pwa-notification-preferences',
    regularUserNotifications: 'regular-user-notifications',
    offlineSync: 'offline-sync',
    syncError: 'pwa-sync-error',
    secondFocusable: 'pwa-second-focusable',
    stateAnnouncement: 'pwa-state-announcement',
    adminUserNotifications: 'admin-user-notifications',
    installError: 'pwa-install-error',
    mobileNotifications: 'mobile-notifications',
  },

  // Accessibility
  accessibility: {
    mainHeading: 'main-heading',
    sectionHeading: 'section-heading',
    searchInput: 'search-input',
    filterButton: 'filter-button',
    feedItem: (id: string) => `feed-item-${id}`,
    liveRegion: 'live-region',
    statusMessage: 'status-message',
    errorMessage: 'error-message',
    alertMessage: 'alert-message',
    loadingIndicator: 'loading-indicator',
    skipLink: 'skip-link',
    focusTrap: 'focus-trap',
    modal: 'modal',
    dialog: 'dialog',
    complementary: 'complementary',
    navigation: 'navigation',
    main: 'main',
    banner: 'banner',
    contentinfo: 'contentinfo',
    form: 'form',
    search: 'search',
    article: 'article',
    region: 'region',
    button: 'button',
    link: 'link',
    textbox: 'textbox',
    checkbox: 'checkbox',
    radio: 'radio',
    select: 'select',
    slider: 'slider',
    progressbar: 'progressbar',
    tablist: 'tablist',
    tab: 'tab',
    tabpanel: 'tabpanel',
    menu: 'menu',
    menuitem: 'menuitem',
    tree: 'tree',
    treeitem: 'treeitem',
    grid: 'grid',
    row: 'row',
    cell: 'cell',
    table: 'table',
    columnheader: 'columnheader',
    rowheader: 'rowheader',
    list: 'list',
    listitem: 'listitem',
    group: 'group',
    separator: 'separator',
    toolbar: 'toolbar',
    tooltip: 'tooltip',
    status: 'status',
    alert: 'alert',
    log: 'log',
    marquee: 'marquee',
    timer: 'timer',
    application: 'application',
    document: 'document',
    presentation: 'presentation',
    img: 'img',
    figure: 'figure',
    caption: 'caption',
    legend: 'legend',
    fieldset: 'fieldset',
    label: 'label',
    description: 'description',
    details: 'details',
    summary: 'summary',
    disclosure: 'disclosure',
    disclosureButton: 'disclosure-button',
    disclosurePanel: 'disclosure-panel',
    combobox: 'combobox',
    listbox: 'listbox',
    option: 'option',
    spinbutton: 'spinbutton',
    switch: 'switch',
  },
  
  // Poll
  poll: {
    item: 'poll-item',
    title: 'poll-title',
    description: 'poll-description',
    results: 'poll-results',
    voteCount: 'vote-count',
    category: 'poll-category',
    privacy: 'poll-privacy',
    timing: 'poll-timing',
    voteError: 'vote-error',
    search: 'poll-search',
    categoryFilter: 'category-filter',
  },
  
  // Navigation
  pollsNav: 'polls-nav',
  profileLink: 'profile-link',
  
  // Dashboard
  dashboard: {
    page: 'dashboard-page',
    header: 'dashboard-header',
    content: 'dashboard-content',
    nav: 'dashboard-nav',
    title: 'dashboard-title',
    userInfo: 'user-info',
    userName: 'user-name',
    userEmail: 'user-email',
    metricsSection: 'metrics-section',
    metricsTitle: 'metrics-title',
    metricsGrid: 'metrics-grid',
    metricPollsCreated: 'metric-polls-created',
    metricVotesCast: 'metric-votes-cast',
    metricParticipation: 'metric-participation',
    metricSessionTime: 'metric-session-time',
    metricValue: 'metric-value',
    metricLabel: 'metric-label',
    pollsSection: 'polls-section',
    pollsHeader: 'polls-header',
    pollsTitle: 'polls-title',
    pollsList: 'polls-list',
    pollItem: (id: string) => `poll-item-${id}`,
    pollTitle: 'poll-title',
    pollStatus: 'poll-status',
    pollVotes: 'poll-votes',
    createPollBtn: 'create-poll-btn',
    recentActivitySection: 'recent-activity-section',
    activityTitle: 'activity-title',
    activityList: 'activity-list',
    activityItem: (id: string) => `activity-item-${id}`,
    activityText: 'activity-text',
    activityTime: 'activity-time',
    navDashboard: 'nav-dashboard',
    navPolls: 'nav-polls',
    navCivics: 'nav-civics',
    navProfile: 'nav-profile',
  },
  
  // Onboarding
  onboarding: {
    flow: 'onboarding-flow',
    progress: 'onboarding-progress',
    currentStep: 'current-step',
    totalSteps: 'total-steps',
    welcomeStep: 'welcome-step',
    welcomeTitle: 'welcome-title',
    welcomeSubtitle: 'welcome-subtitle',
    welcomeNext: 'welcome-next',
    welcomeSkip: 'welcome-skip',
    privacyStep: 'privacy-step',
    privacyTitle: 'privacy-title',
    privacyOptions: 'privacy-options',
    notificationsLabel: 'notifications-label',
    notificationsCheckbox: 'notifications-checkbox',
    dataSharingLabel: 'data-sharing-label',
    dataSharingCheckbox: 'data-sharing-checkbox',
    privacyNext: 'privacy-next',
    privacyBack: 'privacy-back',
    demographicsStep: 'demographics-step',
    demographicsTitle: 'demographics-title',
    demographicsForm: 'demographics-form',
    ageInput: 'age-input',
    genderSelect: 'gender-select',
    locationInput: 'location-input',
    demographicsNext: 'demographics-next',
    demographicsBack: 'demographics-back',
    demographicsSkip: 'demographics-skip',
    authStep: 'auth-step',
    authTitle: 'auth-title',
    authSubtitle: 'auth-subtitle',
    authNext: 'auth-next',
    authBack: 'auth-back',
    profileStep: 'profile-step',
    profileTitle: 'profile-title',
    profileForm: 'profile-form',
    usernameInput: 'username-input',
    bioTextarea: 'bio-textarea',
    profileNext: 'profile-next',
    profileBack: 'profile-back',
    profileSkip: 'profile-skip',
    completeStep: 'complete-step',
    completeTitle: 'complete-title',
    completeSubtitle: 'complete-subtitle',
    completeFinish: 'complete-finish',
    tourNext: 'tour-next',
    dataUsageNext: 'data-usage-next',
    interestsNext: 'interests-next',
    experienceNext: 'experience-next',
  },
  
  // Forms
  registerForm: 'register-form',
  loginForm: 'login-form',
  loginError: 'login-error',
  
  // User
  signUpButton: 'sign-up-button',
  completeOnboarding: 'complete-onboarding',
  biometricSetupButton: 'biometric-setup-button',
  
  // Admin
  adminUsersTab: 'admin-users-tab',
  adminPollsTab: 'admin-polls-tab',
  adminSystemTab: 'admin-system-tab',
  systemStatus: 'system-status',
  deletePollButton: 'delete-poll-button',
  moderatePollButton: 'moderate-poll-button',
  
  // Navigation & UI Components
  hamburgerMenu: 'hamburger-menu',
  themeToggle: 'theme-toggle',
  onlineIndicator: 'online-indicator',
  mainHeading: 'main-heading',
  button: 'button',
  status: 'status',
  
  // Test Toggle (for debugging)
  testToggle: 'test-toggle',
  
  // Login Form
  loginHydrated: 'login-hydrated',
  
  // Onboarding Passkey Setup
  onboardingPasskeySetup: 'onboarding-passkey-setup',
  authPasskeyOption: 'auth-passkey-option',
  authEmailOption: 'auth-email-option',
  authGoogleOption: 'auth-google-option',
  
  // Onboarding Flow Steps
  welcomeNext: 'welcome-next',
  privacyNext: 'privacy-next',
  profileNext: 'profile-next',
  tourNext: 'tour-next',
  dataUsageNext: 'data-usage-next',
  interestsNext: 'interests-next',
  experienceNext: 'experience-next',
  
  // Form Validation & UI Elements
  emailValidation: 'email-validation',
  passwordStrength: 'password-strength',
  passwordMatch: 'password-match',
  displayNameValidation: 'display-name-validation',
  successMessage: 'success-message',
  userAvatar: 'user-avatar',
  emailError: 'email-error',
  passwordError: 'password-error',
  displayNameError: 'display-name-error',
  errorSummary: 'error-summary',
  errorCount: 'error-count',
  passwordToggle: 'password-toggle',
  errorMessage: 'error-message',
  retryButton: 'retry-button',
  mobileMenu: 'mobile-menu',
  csrfToken: 'csrf-token',
  rateLimitMessage: 'rate-limit-message',
} as const;

export type TestId = typeof T[keyof typeof T];