version: '3.8'

services:
  # Identity Authority Service
  ia:
    build:
      context: .
      dockerfile: Dockerfile.ia
    ports:
      - "8081:8081"
    volumes:
      - ia_data:/app/data
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Polling Operator Service
  po:
    build:
      context: .
      dockerfile: Dockerfile.po
    ports:
      - "8082:8082"
    volumes:
      - po_data:/app/data
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      ia:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Web Interface
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_IA_URL=http://ia:8081
      - NEXT_PUBLIC_PO_URL=http://po:8082
    restart: unless-stopped
    depends_on:
      - ia
      - po
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - ia
      - po
    restart: unless-stopped
    profiles:
      - production

volumes:
  ia_data:
    driver: local
  po_data:
    driver: local

networks:
  default:
    name: choices-network
