#!/bin/bash

# Quick Start Script - Your Daily Development Commands

echo "🛠️  Handy Scripts - Quick Start Guide"
echo "====================================="
echo ""

echo "📋 Most Common Commands:"
echo ""
echo "🛡️  SAFE OPERATIONS (Recommended):"
echo "   ./safe-cleanup.sh --fix          # Safe code cleanup"
echo "   ./safe-validation.sh             # Safe pre-push validation"
echo "   ./safe-run.sh <script> [args]    # Run any script safely"
echo ""
echo "🚀 Push & Monitor CI:"
echo "   ./push-and-monitor.sh origin feature/enhanced-feedback-system"
echo ""
echo "📊 Monitor CI Status:"
echo "   ./monitor-ci.sh"
echo ""
echo "✅ Run Local CI Checks:"
echo "   ./pre-push-validation.sh"
echo ""
echo "🧹 Clean Up Code:"
echo "   node cleanup-code.js --fix"
echo ""
echo "📖 View Full Documentation:"
echo "   cat README.md"
echo ""
echo "====================================="
echo "💡 Pro Tip: Use 'push-and-monitor.sh' for the best development experience!"
echo ""
