name: AI Task
description: Work assignment for an AI agent (with contract)
labels: [ai]
body:
  - type: input
    id: date
    attributes: { label: Date (UTC), placeholder: "YYYY-MM-DD" }
    validations: { required: true }
  - type: input
    id: branch
    attributes: { label: Branch name, placeholder: "agent/3-candidates-api" }
    validations: { required: true }
  - type: textarea
    id: contract
    attributes:
      label: Agent Contract
      description: |
        - You may ONLY change files in: <list paths>
        - PR title: type(scope): summary [agent-N]
        - Max LOC per policy; hot-file limit applies
        - Add tests; no new deps; no deploy changes
        - Include **Date (UTC)** in PR body
    validations: { required: true }
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define expected outputs, API contracts, examples
    validations: { required: true }
