name: Bug
description: Something is broken
labels: [fix]
body:
  - type: input
    id: date
    attributes: { label: Date (UTC), placeholder: "YYYY-MM-DD" }
    validations: { required: true }
  - type: input
    id: env
    attributes: { label: Environment, placeholder: "local / preview / prod" }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to Reproduce }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected }
  - type: textarea
    id: actual
    attributes: { label: Actual }
  - type: textarea
    id: logs
    attributes: { label: Logs/Console }
