name: Feature
description: Propose a new feature or enhancement
labels: [feat]
body:
  - type: input
    id: date
    attributes: { label: Date (UTC), placeholder: "YYYY-MM-DD" }
    validations: { required: true }
  - type: textarea
    id: what
    attributes: { label: What, description: One-sentence goal }
    validations: { required: true }
  - type: textarea
    id: why
    attributes: { label: Why, description: Problem this solves }
    validations: { required: true }
  - type: textarea
    id: scope
    attributes: { label: Scope, description: Affected paths & non-goals }
  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      options:
        - label: Contracts defined
        - label: Tests outlined
