-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_contributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid,
  user_id uuid CHECK (user_id = auth.uid()),
  age_bucket text,
  region_bucket text,
  education_bucket text,
  vote_choice integer,
  participation_time interval,
  consent_granted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_contributions_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_contributions_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.polls(id),
  CONSTRAINT analytics_contributions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.analytics_demographics (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  poll_id text NOT NULL,
  demographic_key USER-DEFINED NOT NULL,
  demographic_value text NOT NULL CHECK (length(demographic_value) >= 1 AND length(demographic_value) <= 100),
  vote_count integer DEFAULT 0 CHECK (vote_count >= 0),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT analytics_demographics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.analytics_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_type USER-DEFINED NOT NULL,
  poll_id text,
  user_id uuid,
  metadata jsonb CHECK (metadata IS NULL OR length(metadata::text) <= 10000),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT analytics_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action text NOT NULL,
  table_name text,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.bias_detection_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  media_poll_id uuid,
  detection_type text NOT NULL,
  severity text DEFAULT 'low'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  description text NOT NULL,
  evidence jsonb DEFAULT '[]'::jsonb,
  impact_score numeric DEFAULT 0 CHECK (impact_score >= 0::numeric AND impact_score <= 1::numeric),
  recommendations jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bias_detection_logs_pkey PRIMARY KEY (id),
  CONSTRAINT bias_detection_logs_media_poll_id_fkey FOREIGN KEY (media_poll_id) REFERENCES public.media_polls(id)
);
CREATE TABLE public.biometric_auth_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  credential_id text,
  authentication_result boolean NOT NULL,
  failure_reason text,
  ip_address inet,
  user_agent text,
  device_info jsonb,
  location_info jsonb,
  risk_score numeric DEFAULT 0.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT biometric_auth_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.biometric_trust_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  base_score numeric DEFAULT 0.0,
  device_consistency_score numeric DEFAULT 0.0,
  behavior_score numeric DEFAULT 0.0,
  location_score numeric DEFAULT 0.0,
  overall_score numeric DEFAULT 0.0,
  last_calculated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT biometric_trust_scores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.breaking_news (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  headline text NOT NULL,
  summary text NOT NULL,
  full_story text,
  source_url text,
  source_name text NOT NULL,
  source_reliability numeric DEFAULT 0.9,
  category ARRAY DEFAULT '{}'::text[],
  urgency text DEFAULT 'medium'::text CHECK (urgency = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'breaking'::text])),
  sentiment text DEFAULT 'neutral'::text CHECK (sentiment = ANY (ARRAY['positive'::text, 'negative'::text, 'neutral'::text, 'mixed'::text])),
  entities jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT breaking_news_pkey PRIMARY KEY (id)
);
CREATE TABLE public.campaign_finance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  candidate_id uuid,
  committee_id text,
  committee_name text,
  cycle integer NOT NULL,
  total_receipts numeric DEFAULT 0.0,
  total_disbursements numeric DEFAULT 0.0,
  cash_on_hand numeric DEFAULT 0.0,
  debt numeric DEFAULT 0.0,
  individual_contributions numeric DEFAULT 0.0,
  pac_contributions numeric DEFAULT 0.0,
  party_contributions numeric DEFAULT 0.0,
  self_financing numeric DEFAULT 0.0,
  independence_score numeric DEFAULT 0.0 CHECK (independence_score >= 0::numeric AND independence_score <= 1::numeric),
  top_donor_percentage numeric DEFAULT 0.0,
  corporate_donor_percentage numeric DEFAULT 0.0,
  data_sources ARRAY NOT NULL,
  quality_score numeric DEFAULT 0.0 CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  provenance jsonb DEFAULT '{}'::jsonb,
  license_key text,
  CONSTRAINT campaign_finance_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_finance_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidates(id)
);
CREATE TABLE public.candidates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  canonical_id text NOT NULL UNIQUE,
  name text NOT NULL,
  first_name text,
  last_name text,
  party text CHECK (party = ANY (ARRAY['D'::text, 'R'::text, 'I'::text, 'L'::text, 'G'::text, 'N'::text, 'U'::text])),
  office text NOT NULL,
  chamber text CHECK (chamber = ANY (ARRAY['house'::text, 'senate'::text, 'state_house'::text, 'state_senate'::text, 'local'::text])),
  state text NOT NULL CHECK (length(state) = 2),
  district text,
  level text NOT NULL CHECK (level = ANY (ARRAY['federal'::text, 'state'::text, 'local'::text])),
  email text,
  phone text,
  website text,
  photo_url text,
  social_media jsonb DEFAULT '{}'::jsonb,
  ocd_division_id text,
  jurisdiction_ids ARRAY,
  verified boolean DEFAULT false,
  verification_method text,
  verification_date timestamp with time zone,
  data_sources ARRAY NOT NULL,
  quality_score numeric DEFAULT 0.0 CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  provenance jsonb DEFAULT '{}'::jsonb,
  license_key text,
  CONSTRAINT candidates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civics_addresses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  address_hash text NOT NULL UNIQUE,
  normalized_address text NOT NULL,
  state text,
  district text,
  confidence numeric,
  lat double precision,
  lng double precision,
  reps jsonb,
  sources ARRAY DEFAULT ARRAY['google-civic'::text],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '01:00:00'::interval),
  pepper_version smallint NOT NULL DEFAULT 1,
  CONSTRAINT civics_addresses_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civics_campaign_finance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  candidate_id text NOT NULL,
  candidate_name text NOT NULL,
  office text NOT NULL,
  state text,
  district text,
  party text,
  cycle integer NOT NULL,
  total_receipts numeric,
  total_disbursements numeric,
  cash_on_hand numeric,
  debt numeric,
  raw_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_campaign_finance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civics_divisions (
  ocd_division_id text NOT NULL,
  level text NOT NULL,
  chamber text NOT NULL,
  state text,
  district_number integer,
  name text,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_divisions_pkey PRIMARY KEY (ocd_division_id)
);
CREATE TABLE public.civics_expected_counts (
  id integer NOT NULL DEFAULT nextval('civics_expected_counts_id_seq'::regclass),
  level text NOT NULL,
  jurisdiction text NOT NULL,
  expected_count integer NOT NULL,
  actual_count integer,
  count_date date NOT NULL DEFAULT CURRENT_DATE,
  drift_percentage numeric,
  is_within_threshold boolean,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_expected_counts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civics_fec_minimal (
  id integer NOT NULL DEFAULT nextval('civics_fec_minimal_id_seq'::regclass),
  person_id uuid,
  fec_candidate_id text NOT NULL,
  election_cycle integer NOT NULL,
  total_receipts numeric DEFAULT 0,
  cash_on_hand numeric DEFAULT 0,
  data_source text DEFAULT 'fec_api'::text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_fec_minimal_pkey PRIMARY KEY (id),
  CONSTRAINT civics_fec_minimal_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.civics_person_xref(person_id)
);
CREATE TABLE public.civics_person_xref (
  person_id uuid NOT NULL DEFAULT gen_random_uuid(),
  bioguide text UNIQUE,
  govtrack_id integer UNIQUE,
  openstates_id text UNIQUE,
  fec_candidate_id text UNIQUE,
  propublica_id text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_person_xref_pkey PRIMARY KEY (person_id)
);
CREATE TABLE public.civics_quality_thresholds (
  id integer NOT NULL DEFAULT nextval('civics_quality_thresholds_id_seq'::regclass),
  level text NOT NULL,
  min_quality_score integer DEFAULT 85,
  max_freshness_days integer DEFAULT 7,
  alert_threshold_percentage numeric DEFAULT 2.0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_quality_thresholds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.civics_representatives (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  party text,
  office text NOT NULL,
  level text,
  jurisdiction text,
  district text,
  ocd_division_id text,
  contact jsonb,
  raw_payload jsonb NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  person_id uuid,
  source text,
  external_id text,
  data_origin text DEFAULT 'api'::text,
  valid_from timestamp with time zone DEFAULT now(),
  valid_to timestamp with time zone DEFAULT 'infinity'::timestamp with time zone,
  CONSTRAINT civics_representatives_pkey PRIMARY KEY (id),
  CONSTRAINT fk_representatives_person_id FOREIGN KEY (person_id) REFERENCES public.civics_person_xref(person_id)
);
CREATE TABLE public.civics_source_precedence (
  level text NOT NULL,
  source text NOT NULL,
  precedence_order integer NOT NULL,
  is_active boolean DEFAULT true,
  CONSTRAINT civics_source_precedence_pkey PRIMARY KEY (level, source)
);
CREATE TABLE public.civics_votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  representative_id uuid,
  bill_id text NOT NULL,
  bill_title text,
  vote_position text NOT NULL,
  vote_date date NOT NULL,
  chamber text NOT NULL,
  session text,
  raw_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_votes_pkey PRIMARY KEY (id),
  CONSTRAINT civics_votes_representative_id_fkey FOREIGN KEY (representative_id) REFERENCES public.civics_representatives(id)
);
CREATE TABLE public.civics_votes_minimal (
  id integer NOT NULL DEFAULT nextval('civics_votes_minimal_id_seq'::regclass),
  person_id uuid,
  vote_id text NOT NULL,
  bill_title text,
  vote_date date NOT NULL,
  vote_position text NOT NULL,
  party_position text,
  chamber text NOT NULL,
  data_source text DEFAULT 'govtrack_api'::text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT civics_votes_minimal_pkey PRIMARY KEY (id),
  CONSTRAINT civics_votes_minimal_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.civics_person_xref(person_id)
);
CREATE TABLE public.contributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  candidate_id uuid,
  committee_id text,
  contributor_name_hash text,
  contributor_city text,
  contributor_state text CHECK (length(contributor_state) = 2),
  contributor_zip5 text,
  contributor_employer text,
  contributor_occupation text,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  contribution_date date NOT NULL,
  contribution_type text CHECK (contribution_type = ANY (ARRAY['individual'::text, 'pac'::text, 'party'::text, 'self'::text])),
  sector text,
  industry text,
  data_sources ARRAY NOT NULL,
  quality_score numeric DEFAULT 0.0 CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  provenance jsonb DEFAULT '{}'::jsonb,
  license_key text,
  retention_until date,
  CONSTRAINT contributions_pkey PRIMARY KEY (id),
  CONSTRAINT contributions_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidates(id)
);
CREATE TABLE public.data_checksums (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  checksum_type text NOT NULL CHECK (checksum_type = ANY (ARRAY['md5'::text, 'sha256'::text, 'crc32'::text])),
  checksum_value text NOT NULL,
  data_snapshot jsonb,
  calculated_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_checksums_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_licenses (
  license_key text NOT NULL,
  source_name text NOT NULL,
  attribution_text text NOT NULL,
  display_requirements text,
  cache_ttl_seconds integer,
  usage_restrictions jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_licenses_pkey PRIMARY KEY (license_key)
);
CREATE TABLE public.data_lineage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_table text NOT NULL,
  source_record_id uuid NOT NULL,
  target_table text NOT NULL,
  target_record_id uuid NOT NULL,
  transformation_type text NOT NULL CHECK (transformation_type = ANY (ARRAY['insert'::text, 'update'::text, 'delete'::text, 'merge'::text, 'deduplicate'::text])),
  transformation_version text NOT NULL,
  transformation_params jsonb,
  source_data_hash text,
  target_data_hash text,
  processing_started_at timestamp with time zone NOT NULL,
  processing_completed_at timestamp with time zone,
  processing_duration_ms integer,
  success boolean DEFAULT false,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_lineage_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_quality_audit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  completeness_score numeric DEFAULT 0.0 CHECK (completeness_score >= 0::numeric AND completeness_score <= 1::numeric),
  accuracy_score numeric DEFAULT 0.0 CHECK (accuracy_score >= 0::numeric AND accuracy_score <= 1::numeric),
  consistency_score numeric DEFAULT 0.0 CHECK (consistency_score >= 0::numeric AND consistency_score <= 1::numeric),
  timeliness_score numeric DEFAULT 0.0 CHECK (timeliness_score >= 0::numeric AND timeliness_score <= 1::numeric),
  overall_score numeric DEFAULT 0.0 CHECK (overall_score >= 0::numeric AND overall_score <= 1::numeric),
  primary_source text,
  secondary_sources ARRAY,
  conflict_resolution text,
  last_validation timestamp with time zone DEFAULT now(),
  validation_method text,
  issues_found ARRAY,
  resolved_issues ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_quality_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_quality_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  check_name text NOT NULL,
  check_type text NOT NULL CHECK (check_type = ANY (ARRAY['schema'::text, 'completeness'::text, 'accuracy'::text, 'consistency'::text, 'timeliness'::text, 'uniqueness'::text, 'referential_integrity'::text])),
  table_name text NOT NULL,
  record_id uuid,
  check_params jsonb,
  expected_result text,
  actual_result text,
  passed boolean NOT NULL,
  severity text CHECK (severity = ANY (ARRAY['error'::text, 'warning'::text, 'info'::text])),
  error_message text,
  suggested_fix text,
  check_executed_at timestamp with time zone NOT NULL,
  check_version text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_quality_checks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  type text NOT NULL CHECK (type = ANY (ARRAY['news'::text, 'social'::text, 'search'::text, 'academic'::text])),
  api_endpoint text,
  api_key text,
  rate_limit integer DEFAULT 1000,
  reliability numeric DEFAULT 0.9,
  is_active boolean DEFAULT true,
  last_updated timestamp with time zone DEFAULT now(),
  error_count integer DEFAULT 0,
  success_rate numeric DEFAULT 100.0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.data_transformations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  transformation_name text NOT NULL,
  transformation_version text NOT NULL,
  source_system text NOT NULL,
  target_system text NOT NULL,
  transformation_sql text,
  transformation_params jsonb,
  input_records_count integer,
  output_records_count integer,
  error_records_count integer,
  processing_started_at timestamp with time zone NOT NULL,
  processing_completed_at timestamp with time zone,
  processing_duration_ms integer,
  success boolean DEFAULT false,
  error_message text,
  retry_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT data_transformations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dbt_freshness_sla (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL UNIQUE,
  max_age_hours integer NOT NULL,
  warning_threshold_hours integer,
  enabled boolean DEFAULT true,
  last_check timestamp with time zone,
  last_success timestamp with time zone,
  last_failure timestamp with time zone,
  consecutive_failures integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dbt_freshness_sla_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dbt_test_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  test_name text NOT NULL UNIQUE,
  test_type text NOT NULL,
  table_name text NOT NULL,
  column_name text,
  test_config jsonb DEFAULT '{}'::jsonb,
  enabled boolean DEFAULT true,
  severity text DEFAULT 'error'::text CHECK (severity = ANY (ARRAY['error'::text, 'warn'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dbt_test_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dbt_test_execution_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  execution_id uuid NOT NULL,
  test_name text NOT NULL,
  status text NOT NULL,
  message text,
  execution_time_ms integer,
  executed_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dbt_test_execution_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dbt_test_results (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  test_name text NOT NULL,
  test_type text NOT NULL CHECK (test_type = ANY (ARRAY['unique'::text, 'not_null'::text, 'accepted_values'::text, 'relationships'::text, 'freshness'::text, 'custom'::text])),
  table_name text NOT NULL,
  column_name text,
  test_config jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL CHECK (status = ANY (ARRAY['pass'::text, 'fail'::text, 'error'::text, 'warn'::text])),
  message text,
  rows_affected bigint,
  execution_time_ms integer,
  executed_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT dbt_test_results_pkey PRIMARY KEY (id)
);
CREATE TABLE public.elections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  canonical_id text NOT NULL UNIQUE,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['general'::text, 'primary'::text, 'special'::text, 'runoff'::text])),
  level text NOT NULL CHECK (level = ANY (ARRAY['federal'::text, 'state'::text, 'local'::text])),
  state text NOT NULL CHECK (length(state) = 2),
  district text,
  election_date date NOT NULL,
  registration_deadline date,
  early_voting_start date,
  early_voting_end date,
  ocd_division_id text,
  jurisdiction_ids ARRAY,
  status text DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'active'::text, 'completed'::text])),
  results_available boolean DEFAULT false,
  data_sources ARRAY NOT NULL,
  quality_score numeric DEFAULT 0.0 CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  provenance jsonb DEFAULT '{}'::jsonb,
  license_key text,
  CONSTRAINT elections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.error_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  error_type text NOT NULL,
  error_message text NOT NULL,
  stack_trace text,
  context jsonb DEFAULT '{}'::jsonb,
  severity text NOT NULL CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT error_logs_pkey PRIMARY KEY (id),
  CONSTRAINT error_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.fact_check_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  url text,
  reliability numeric DEFAULT 0.5 CHECK (reliability >= 0::numeric AND reliability <= 1::numeric),
  bias text,
  fact_check_rating text DEFAULT 'unknown'::text CHECK (fact_check_rating = ANY (ARRAY['reliable'::text, 'mixed'::text, 'unreliable'::text, 'unknown'::text])),
  api_endpoint text,
  api_key text,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fact_check_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fec_candidate_committee (
  fec_candidate_id text NOT NULL,
  fec_committee_id text NOT NULL,
  designation text CHECK (designation = ANY (ARRAY['P'::text, 'A'::text, 'J'::text, 'B'::text, 'D'::text, 'U'::text])),
  cycle integer NOT NULL,
  committee_name text,
  committee_type text,
  committee_designation text,
  committee_organization_type text,
  candidate_name text,
  candidate_office text,
  candidate_state text,
  candidate_district text,
  candidate_party text,
  candidate_status text,
  candidate_incumbent_challenge_status text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fec_candidate_committee_pkey PRIMARY KEY (cycle, fec_committee_id, fec_candidate_id)
);
CREATE TABLE public.fec_candidates (
  candidate_id text NOT NULL,
  name text NOT NULL,
  office text,
  party text,
  state text,
  district text,
  incumbent_challenge_status text,
  candidate_status text,
  candidate_inactive text,
  election_years ARRAY,
  election_districts ARRAY,
  first_file_date date,
  last_file_date date,
  last_f2_date date,
  active_through integer,
  principal_committees ARRAY,
  authorized_committees ARRAY,
  total_receipts numeric DEFAULT 0.0,
  total_disbursements numeric DEFAULT 0.0,
  cash_on_hand numeric DEFAULT 0.0,
  debt numeric DEFAULT 0.0,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  data_source text DEFAULT 'fec'::text,
  is_efiling boolean DEFAULT false,
  is_processed boolean DEFAULT true,
  provenance jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fec_candidates_pkey PRIMARY KEY (candidate_id)
);
CREATE TABLE public.fec_committees (
  committee_id text NOT NULL,
  committee_name text NOT NULL,
  committee_type text,
  committee_designation text,
  committee_organization_type text,
  committee_party text,
  committee_state text,
  committee_district text,
  treasurer_name text,
  treasurer_city text,
  treasurer_state text,
  treasurer_zip text,
  custodian_name text,
  custodian_city text,
  custodian_state text,
  custodian_zip text,
  street_1 text,
  street_2 text,
  city text,
  state text,
  zip text,
  candidate_id text,
  candidate_name text,
  candidate_office text,
  candidate_state text,
  candidate_district text,
  candidate_party text,
  candidate_status text,
  candidate_incumbent_challenge_status text,
  first_file_date date,
  last_file_date date,
  last_f1_date date,
  organization_type text,
  organization_type_full text,
  designation text,
  designation_full text,
  committee_type_full text,
  party_full text,
  filing_frequency text,
  filing_frequency_full text,
  cycles ARRAY,
  total_receipts numeric DEFAULT 0.0,
  total_disbursements numeric DEFAULT 0.0,
  cash_on_hand numeric DEFAULT 0.0,
  debt numeric DEFAULT 0.0,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  data_source text DEFAULT 'fec'::text,
  is_efiling boolean DEFAULT false,
  is_processed boolean DEFAULT true,
  provenance jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fec_committees_pkey PRIMARY KEY (committee_id)
);
CREATE TABLE public.fec_contributions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  committee_id text NOT NULL,
  candidate_id text,
  contributor_name text,
  contributor_name_normalized text,
  contributor_city text,
  contributor_state text,
  contributor_zip text,
  contributor_employer text,
  contributor_occupation text,
  contributor_organization_name text,
  contributor_organization_type text,
  contributor_committee_id text,
  contributor_committee_name text,
  contributor_committee_type text,
  contributor_committee_designation text,
  contributor_committee_organization_type text,
  contributor_committee_party text,
  contributor_committee_state text,
  contributor_committee_district text,
  amount numeric NOT NULL,
  contribution_date date NOT NULL,
  contribution_type text,
  contribution_type_desc text,
  memo_code text,
  memo_text text,
  receipt_type text,
  receipt_type_desc text,
  receipt_type_full text,
  line_number text,
  transaction_id text,
  file_number text,
  report_type text,
  report_type_full text,
  report_year integer,
  two_year_transaction_period integer NOT NULL,
  cycle integer NOT NULL,
  sub_id text,
  link_id text,
  image_number text,
  file_number_raw text,
  is_individual boolean,
  is_corporate boolean,
  is_pac boolean,
  is_party boolean,
  is_self_financing boolean,
  sector text,
  industry text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  data_source text DEFAULT 'fec'::text,
  is_efiling boolean DEFAULT false,
  is_processed boolean DEFAULT true,
  provenance jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fec_contributions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fec_cycles (
  cycle integer NOT NULL,
  cycle_name text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  election_date date NOT NULL,
  is_current boolean DEFAULT false,
  is_upcoming boolean DEFAULT false,
  is_completed boolean DEFAULT false,
  data_available boolean DEFAULT false,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fec_cycles_pkey PRIMARY KEY (cycle)
);
CREATE TABLE public.fec_disbursements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  committee_id text NOT NULL,
  candidate_id text,
  recipient_name text,
  recipient_name_normalized text,
  recipient_city text,
  recipient_state text,
  recipient_zip text,
  recipient_employer text,
  recipient_occupation text,
  recipient_organization_name text,
  recipient_organization_type text,
  recipient_committee_id text,
  recipient_committee_name text,
  recipient_committee_type text,
  recipient_committee_designation text,
  recipient_committee_organization_type text,
  recipient_committee_party text,
  recipient_committee_state text,
  recipient_committee_district text,
  amount numeric NOT NULL,
  disbursement_date date NOT NULL,
  disbursement_type text,
  disbursement_type_desc text,
  memo_code text,
  memo_text text,
  receipt_type text,
  receipt_type_desc text,
  receipt_type_full text,
  line_number text,
  transaction_id text,
  file_number text,
  report_type text,
  report_type_full text,
  report_year integer,
  two_year_transaction_period integer NOT NULL,
  cycle integer NOT NULL,
  sub_id text,
  link_id text,
  image_number text,
  file_number_raw text,
  purpose text,
  purpose_desc text,
  category text,
  category_desc text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  data_source text DEFAULT 'fec'::text,
  is_efiling boolean DEFAULT false,
  is_processed boolean DEFAULT true,
  provenance jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fec_disbursements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fec_independent_expenditures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  committee_id text NOT NULL,
  candidate_id text,
  candidate_name text,
  candidate_office text,
  candidate_state text,
  candidate_district text,
  candidate_party text,
  candidate_status text,
  candidate_incumbent_challenge_status text,
  spender_name text,
  spender_city text,
  spender_state text,
  spender_zip text,
  spender_employer text,
  spender_occupation text,
  spender_organization_name text,
  spender_organization_type text,
  spender_committee_id text,
  spender_committee_name text,
  spender_committee_type text,
  spender_committee_designation text,
  spender_committee_organization_type text,
  spender_committee_party text,
  spender_committee_state text,
  spender_committee_district text,
  amount numeric NOT NULL,
  expenditure_date date NOT NULL,
  expenditure_type text,
  expenditure_type_desc text,
  memo_code text,
  memo_text text,
  receipt_type text,
  receipt_type_desc text,
  receipt_type_full text,
  line_number text,
  transaction_id text,
  file_number text,
  report_type text,
  report_type_full text,
  report_year integer,
  two_year_transaction_period integer NOT NULL,
  cycle integer NOT NULL,
  sub_id text,
  link_id text,
  image_number text,
  file_number_raw text,
  purpose text,
  purpose_desc text,
  category text,
  category_desc text,
  support_oppose_indicator text,
  support_oppose_indicator_desc text,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  data_source text DEFAULT 'fec'::text,
  is_efiling boolean DEFAULT false,
  is_processed boolean DEFAULT true,
  provenance jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT fec_independent_expenditures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fec_ingest_cursors (
  source text NOT NULL,
  cycle integer NOT NULL,
  cursor_type text NOT NULL,
  cursor_value text NOT NULL,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fec_ingest_cursors_pkey PRIMARY KEY (cursor_type, source, cycle)
);
CREATE TABLE public.feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  poll_id uuid,
  topic_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['bug'::text, 'feature'::text, 'general'::text, 'performance'::text, 'accessibility'::text, 'security'::text, 'test'::text])),
  rating integer CHECK (rating >= 1 AND rating <= 5),
  description text CHECK (char_length(description) <= 1000),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  ai_analysis jsonb DEFAULT '{}'::jsonb,
  user_journey jsonb DEFAULT '{}'::jsonb,
  screenshot text,
  status text DEFAULT 'open'::text,
  priority text DEFAULT 'medium'::text,
  tags ARRAY DEFAULT '{}'::text[],
  updated_at timestamp with time zone DEFAULT now(),
  sentiment text CHECK (char_length(sentiment) <= 20),
  title text CHECK (char_length(title) <= 200),
  CONSTRAINT feedback_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT feedback_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.generated_polls(id),
  CONSTRAINT feedback_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.trending_topics(id)
);
CREATE TABLE public.generated_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_id uuid,
  title text NOT NULL,
  description text,
  options jsonb NOT NULL,
  voting_method text NOT NULL CHECK (voting_method = ANY (ARRAY['single'::text, 'multiple'::text, 'ranked'::text, 'approval'::text, 'range'::text, 'quadratic'::text])),
  category text,
  tags ARRAY DEFAULT '{}'::text[],
  quality_score numeric DEFAULT 0.0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending'::text, 'approved'::text, 'rejected'::text, 'active'::text, 'closed'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  topic_analysis jsonb DEFAULT '{}'::jsonb,
  quality_metrics jsonb DEFAULT '{}'::jsonb,
  generation_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT generated_polls_pkey PRIMARY KEY (id),
  CONSTRAINT generated_polls_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.trending_topics(id),
  CONSTRAINT generated_polls_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.id_crosswalk (
  entity_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type text NOT NULL CHECK (entity_type = ANY (ARRAY['person'::text, 'committee'::text, 'bill'::text, 'jurisdiction'::text, 'election'::text])),
  canonical_id text NOT NULL,
  source text NOT NULL,
  source_id text NOT NULL,
  attrs jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT id_crosswalk_pkey PRIMARY KEY (entity_uuid)
);
CREATE TABLE public.idempotency_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  result_data jsonb,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.independence_score_methodology (
  version text NOT NULL,
  formula text NOT NULL,
  data_sources ARRAY NOT NULL,
  confidence_interval numeric,
  experimental boolean DEFAULT true,
  methodology_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT independence_score_methodology_pkey PRIMARY KEY (version)
);
CREATE TABLE public.ingest_cursors (
  source text NOT NULL,
  cursor jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ingest_cursors_pkey PRIMARY KEY (source)
);
CREATE TABLE public.latlon_to_ocd (
  lat numeric NOT NULL,
  lon numeric NOT NULL,
  ocd_division_id text NOT NULL,
  confidence numeric DEFAULT 0.0 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT latlon_to_ocd_pkey PRIMARY KEY (lon, lat)
);
CREATE TABLE public.media_polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  headline text NOT NULL,
  question text NOT NULL,
  options jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_id uuid,
  source_data jsonb NOT NULL,
  methodology jsonb NOT NULL,
  results jsonb NOT NULL,
  bias_analysis jsonb DEFAULT '{}'::jsonb,
  bias_indicators jsonb DEFAULT '[]'::jsonb,
  fact_check jsonb DEFAULT '{}'::jsonb,
  propaganda_techniques jsonb DEFAULT '[]'::jsonb,
  manipulation_score numeric DEFAULT 0 CHECK (manipulation_score >= 0::numeric AND manipulation_score <= 1::numeric),
  overall_bias_score numeric DEFAULT 0 CHECK (overall_bias_score >= 0::numeric AND overall_bias_score <= 1::numeric),
  url text,
  published_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_polls_pkey PRIMARY KEY (id),
  CONSTRAINT media_polls_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.media_sources(id)
);
CREATE TABLE public.media_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id text NOT NULL UNIQUE,
  name text NOT NULL,
  network text NOT NULL,
  bias text DEFAULT 'unknown'::text CHECK (bias = ANY (ARRAY['left'::text, 'center-left'::text, 'center'::text, 'center-right'::text, 'right'::text, 'unknown'::text])),
  reliability numeric DEFAULT 0.5 CHECK (reliability >= 0::numeric AND reliability <= 1::numeric),
  ownership text,
  funding jsonb DEFAULT '[]'::jsonb,
  political_affiliations jsonb DEFAULT '[]'::jsonb,
  fact_check_rating text DEFAULT 'unknown'::text CHECK (fact_check_rating = ANY (ARRAY['reliable'::text, 'mixed'::text, 'unreliable'::text, 'unknown'::text])),
  propaganda_indicators jsonb DEFAULT '[]'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.migration_log (
  id integer NOT NULL DEFAULT nextval('migration_log_id_seq'::regclass),
  migration_name text NOT NULL,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL,
  details text,
  execution_time_ms integer,
  error_message text,
  CONSTRAINT migration_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.news_fetch_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_id uuid,
  fetch_type text NOT NULL CHECK (fetch_type = ANY (ARRAY['manual'::text, 'scheduled'::text, 'real_time'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  articles_found integer DEFAULT 0,
  articles_processed integer DEFAULT 0,
  error_message text,
  processing_time_ms integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT news_fetch_logs_pkey PRIMARY KEY (id),
  CONSTRAINT news_fetch_logs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.news_sources(id)
);
CREATE TABLE public.news_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  domain text NOT NULL,
  reliability numeric DEFAULT 0.9,
  bias text DEFAULT 'unknown'::text CHECK (bias = ANY (ARRAY['left'::text, 'center-left'::text, 'center'::text, 'center-right'::text, 'right'::text, 'unknown'::text])),
  type text DEFAULT 'mainstream'::text CHECK (type = ANY (ARRAY['mainstream'::text, 'wire'::text, 'digital'::text, 'international'::text])),
  api_endpoint text,
  api_key text,
  rate_limit integer DEFAULT 1000,
  is_active boolean DEFAULT true,
  last_updated timestamp with time zone DEFAULT now(),
  error_count integer DEFAULT 0,
  success_rate numeric DEFAULT 100.0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT news_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.poll_contexts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  story_id uuid,
  question text NOT NULL,
  context text NOT NULL,
  why_important text NOT NULL,
  stakeholders jsonb DEFAULT '{}'::jsonb,
  options jsonb NOT NULL,
  voting_method text NOT NULL CHECK (voting_method = ANY (ARRAY['single'::text, 'multiple'::text, 'ranked'::text, 'approval'::text, 'range'::text])),
  estimated_controversy numeric DEFAULT 0.5,
  time_to_live integer DEFAULT 24,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'expired'::text, 'archived'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT poll_contexts_pkey PRIMARY KEY (id),
  CONSTRAINT poll_contexts_story_id_fkey FOREIGN KEY (story_id) REFERENCES public.breaking_news(id)
);
CREATE TABLE public.poll_generation_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  topic_id uuid,
  poll_id uuid,
  generation_step text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text])),
  error_message text,
  processing_time_ms integer,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT poll_generation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT poll_generation_logs_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.trending_topics(id),
  CONSTRAINT poll_generation_logs_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.generated_polls(id)
);
CREATE TABLE public.polls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  options jsonb NOT NULL,
  voting_method text NOT NULL CHECK (voting_method = ANY (ARRAY['single'::text, 'multiple'::text, 'ranked'::text, 'approval'::text, 'range'::text, 'quadratic'::text])),
  privacy_level text NOT NULL DEFAULT 'public'::text CHECK (privacy_level = ANY (ARRAY['public'::text, 'private'::text, 'invite-only'::text])),
  category text DEFAULT 'general'::text,
  tags ARRAY DEFAULT '{}'::text[],
  created_by uuid NOT NULL,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'closed'::text, 'archived'::text])),
  total_votes integer DEFAULT 0,
  participation integer DEFAULT 0,
  sponsors ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone,
  is_mock boolean DEFAULT false,
  settings jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT polls_pkey PRIMARY KEY (id),
  CONSTRAINT polls_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.privacy_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action text NOT NULL,
  user_id_hash text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT privacy_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.private_user_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid CHECK (user_id = auth.uid()),
  encrypted_personal_info bytea,
  encrypted_behavioral_data bytea,
  encrypted_analytics_data bytea,
  encryption_key_hash text,
  last_encrypted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT private_user_data_pkey PRIMARY KEY (id),
  CONSTRAINT private_user_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.quality_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid,
  bias_score numeric DEFAULT 0.0,
  clarity_score numeric DEFAULT 0.0,
  completeness_score numeric DEFAULT 0.0,
  relevance_score numeric DEFAULT 0.0,
  controversy_score numeric DEFAULT 0.0,
  overall_score numeric DEFAULT 0.0,
  assessment_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quality_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT quality_metrics_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.generated_polls(id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ip_address inet NOT NULL,
  endpoint text NOT NULL,
  request_count integer DEFAULT 1,
  window_start timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.redistricting_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  state text NOT NULL CHECK (length(state) = 2),
  district_type text NOT NULL CHECK (district_type = ANY (ARRAY['congressional'::text, 'state_house'::text, 'state_senate'::text])),
  old_district text,
  new_district text,
  census_cycle_from integer NOT NULL,
  census_cycle_to integer NOT NULL,
  change_type text CHECK (change_type = ANY (ARRAY['split'::text, 'merge'::text, 'redraw'::text, 'eliminate'::text, 'create'::text])),
  change_description text,
  effective_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT redistricting_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  operation text NOT NULL,
  user_id uuid,
  ip_address inet,
  user_agent text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT security_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.site_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['info'::text, 'warning'::text, 'success'::text, 'error'::text, 'feedback'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.state_districts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  state text NOT NULL CHECK (length(state) = 2),
  district_type text NOT NULL CHECK (district_type = ANY (ARRAY['congressional'::text, 'state_house'::text, 'state_senate'::text, 'county'::text, 'city'::text])),
  district_number text,
  ocd_division_id text NOT NULL,
  census_cycle integer NOT NULL,
  congress_number integer,
  valid_from date NOT NULL,
  valid_to date,
  is_current boolean DEFAULT (valid_to IS NULL),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT state_districts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_configuration (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_configuration_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trending_topics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  source_url text,
  source_name text NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['news'::text, 'social'::text, 'search'::text, 'academic'::text])),
  category ARRAY DEFAULT '{}'::text[],
  trending_score numeric DEFAULT 0.0,
  velocity numeric DEFAULT 0.0,
  momentum numeric DEFAULT 0.0,
  sentiment_score numeric DEFAULT 0.0,
  entities jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  processing_status text DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  analysis_data jsonb DEFAULT '{}'::jsonb,
  last_processed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trending_topics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_consent (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid CHECK (user_id = auth.uid()),
  consent_type text NOT NULL CHECK (consent_type = ANY (ARRAY['analytics'::text, 'demographics'::text, 'behavioral'::text, 'contact'::text, 'research'::text, 'marketing'::text])),
  granted boolean NOT NULL,
  granted_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  consent_version integer DEFAULT 1,
  purpose text NOT NULL,
  data_types ARRAY NOT NULL DEFAULT '{}'::text[],
  CONSTRAINT user_consent_pkey PRIMARY KEY (id),
  CONSTRAINT user_consent_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  username text NOT NULL UNIQUE,
  email text NOT NULL,
  trust_tier text NOT NULL DEFAULT 'T0'::text CHECK (trust_tier = ANY (ARRAY['T0'::text, 'T1'::text, 'T2'::text, 'T3'::text])),
  avatar_url text,
  bio text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_admin boolean DEFAULT false,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles_encrypted (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE CHECK (user_id = auth.uid()),
  username text UNIQUE,
  public_bio text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  encrypted_demographics bytea,
  encrypted_preferences bytea,
  encrypted_contact_info bytea,
  encryption_version integer DEFAULT 1,
  key_derivation_salt bytea,
  key_hash text,
  CONSTRAINT user_profiles_encrypted_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_encrypted_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.votes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  poll_id uuid NOT NULL,
  user_id uuid NOT NULL,
  choice integer NOT NULL,
  voting_method text NOT NULL CHECK (voting_method = ANY (ARRAY['single'::text, 'multiple'::text, 'ranked'::text, 'approval'::text, 'range'::text, 'quadratic'::text])),
  vote_data jsonb DEFAULT '{}'::jsonb,
  verification_token text,
  is_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT votes_pkey PRIMARY KEY (id),
  CONSTRAINT votes_poll_id_fkey FOREIGN KEY (poll_id) REFERENCES public.polls(id),
  CONSTRAINT votes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.voting_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  candidate_id uuid,
  bill_id text,
  bill_title text,
  bill_subject text,
  vote text NOT NULL CHECK (vote = ANY (ARRAY['yea'::text, 'nay'::text, 'present'::text, 'not_voting'::text])),
  vote_date date NOT NULL,
  chamber text,
  bill_type text CHECK (bill_type = ANY (ARRAY['house'::text, 'senate'::text, 'concurrent'::text])),
  bill_number text,
  congress_number integer,
  vote_description text,
  vote_question text,
  data_sources ARRAY NOT NULL,
  quality_score numeric DEFAULT 0.0 CHECK (quality_score >= 0::numeric AND quality_score <= 1::numeric),
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  provenance jsonb DEFAULT '{}'::jsonb,
  license_key text,
  CONSTRAINT voting_records_pkey PRIMARY KEY (id),
  CONSTRAINT voting_records_candidate_id_fkey FOREIGN KEY (candidate_id) REFERENCES public.candidates(id)
);
CREATE TABLE public.webauthn_challenges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  rp_id text NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['registration'::text, 'authentication'::text])),
  challenge bytea NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  used_at timestamp with time zone,
  origin text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webauthn_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT webauthn_challenges_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.webauthn_credentials (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  rp_id text NOT NULL,
  credential_id bytea NOT NULL UNIQUE,
  public_key bytea NOT NULL,
  cose_alg smallint,
  counter bigint NOT NULL DEFAULT 0,
  transports ARRAY DEFAULT '{}'::text[],
  aaguid uuid,
  backed_up boolean,
  backup_eligible boolean,
  device_label text,
  device_info jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone,
  CONSTRAINT webauthn_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT webauthn_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.zip_to_ocd (
  zip5 text NOT NULL,
  ocd_division_id text NOT NULL,
  confidence numeric DEFAULT 0.0 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT zip_to_ocd_pkey PRIMARY KEY (zip5)
);