# GitHub Pages Configuration
title: Choices - Privacy-First Voting Platform
description: A comprehensive, privacy-first voting and polling platform with advanced security, real-time features, and production-ready deployment.
url: "https://your-username.github.io"
baseurl: "/Choices"

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO
author:
  name: Choices Platform Team
  email: team@choices-platform.com

# Social media
social:
  github: your-username
  twitter: choices_platform

# Analytics (optional)
google_analytics: UA-XXXXXXXXX-X

# Exclude from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
