name: Labels
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]
permissions:
  pull-requests: write
  contents: read
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Add owner-review label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "owner-review"
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Label AI PRs by branch
        if: startsWith(github.event.pull_request.head.ref, 'agent/')
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "ai"
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Add area labels based on changed files
        run: |
          # Get changed files
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD || echo "")
          
          # Add area labels based on file paths
          if echo "$CHANGED_FILES" | grep -q "^apps/web/"; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "area:web"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^apps/ingest/"; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "area:ingest"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^packages/civics-"; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "area:civics"
          fi
          
          if echo "$CHANGED_FILES" | grep -q "^apps/web/app/(api|auth)/"; then
            gh pr edit ${{ github.event.pull_request.number }} --add-label "area:auth"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
