name: Security Watch
on:
  schedule:
    - cron: "7 10 * * 3"  # Wednesdays
  workflow_dispatch:
jobs:
  advisories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for advisories (OSV) for Go and npm
        uses: google/osv-scanner-action@v1
        with:
          scan-args: |
            -r .
