name: Security Watch

on:
  schedule:
    - cron: "0 2 * * *"  # Daily at 2 AM UTC
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm ci

      - name: Run security audit
        run: |
          echo "Running npm security audit..."
          npm audit --audit-level=high || {
            echo "::error::High or critical vulnerabilities detected"
            npm audit --json > audit-results.json
            cat audit-results.json
            exit 1
          }
          echo "✅ No high/critical vulnerabilities found"
      
      - name: Dependency review (disabled for private repo)
        run: |
          echo "⚠️  Dependency review disabled for private repositories"
          echo "To enable: Go to Settings > Security > Code security and analysis"
          echo "Enable 'Dependency graph' and 'Dependabot alerts'"
          echo "Then uncomment the dependency-review-action step below"
        
      # - name: Dependency review
      #   uses: actions/dependency-review-action@v4
      #   if: github.event_name == 'pull_request' && github.repository_visibility == 'public'
      #   with:
      #     fail-on-severity: moderate
      #     allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, Unlicense
