name: Standards Watch
on:
  schedule:
    - cron: "32 9 * * *"  # daily 09:32 UTC
  workflow_dispatch:
jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check standards endpoints for changes
        run: |
          set -euo pipefail
          mkdir -p .cache
          urls=(
            "https://www.w3.org/TR/webauthn-3/"
            "https://datatracker.ietf.org/doc/rfc9576/"
            "https://datatracker.ietf.org/doc/rfc9578/"
            "https://datatracker.ietf.org/doc/rfc9497/"
            "https://www.w3.org/TR/vc-data-model-2.0/"
            "https://pages.nist.gov/800-63-4/"
          )
          changed=0
          for u in "${urls[@]}"; do
            f=".cache/$(echo "$u" | sha256sum | cut -d' ' -f1)"
            curl -sI "$u" | tr -d '\r' > headers.tmp
            if [ ! -f "$f" ] || ! diff -q headers.tmp "$f" >/dev/null 2>&1; then
              changed=1
              cp headers.tmp "$f"
              echo "* Updated: $u" >> changes.txt
            fi
          done
          if [ "$changed" -eq 1 ]; then
            msg="chore(standards): detected standards page updates"
            git config user.name "choice-bot"
            git config user.email "choice-bot@users.noreply.github.com"
            git add .cache changes.txt || true
            git commit -m "$msg" || echo "no changes to commit"
          else
            echo "No changes."
          fi
